### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by Pyrbu** [PikaMug/PacketNPC#2]
Hi! I saw you in the ZNetwork discord a couple days ago advertising this repository, my understanding is that you got banned which is exactly what happened to me too. I would like to invite you to come work on the fork that me and a couple friends have been working on since it is much farther along than your current one. https://github.com/Pyrbu/ZNPCsPlus

**Comment by PikaMug** [comment]
Hello, thanks for reaching out! Yes, a surprise considering the author announced their departure effective immediately. Note that if you're sticking with the Apache license it may not be wise to use "ZNPCs" in the name as it explicitly prevents trademark use (IANAL). Will likely have a PR for you to review soon :)
